Import('env')
Import('build_target')

SConscript('vendor/SConscript')

env.Object(target='main', source=['main.c'])
env.Object(target='lua_wrapper', source=['lua_wrapper.c'])
env.Object(target='lua_frontend', source=['lua_frontend.c'])
env.Object(target='str', source=['str.c'])
# env.Object(target='list', source=['list.c'])
